# Generated by Django 4.2.3 on 2023-08-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='todoitem',
            order_with_respect_to='user',
        ),
    ]
